### PR TITLE
this is not how hooks work

### PR DESCRIPTION
**Pull request by DaaOtt**
"NOBODY ELSE GETS TO LOOK AT TOOLS IT'S ALL MINE"

### CODE REVIEW

**Comment by TylerB260** [comment]
:+1:

**Comment by Domii894** [comment]
Hello DaaOtt,

of course we know how hooks work. Else we wouldn't use them. In this case we returned a boolen to PREVENT that other prop protection/addons like "upp" or similar addons can change it. Sometimes it happens that other addons are returning a boolean and then it gives a fuck on that if it is allowed by PatchProtect and not by another addon.

I hope you understand why I implemented it. Sure, I could delete it, but why should I do it?

**Comment by DaaOtt** [comment]
@FPtje

**Comment by DaaOtt** [comment]
The default behavior is to allow the player to use a tool. When you return true, you completely cut off any chances for other addons to even *see* that the player used the tool. You're causing more problems than fixing them by cutting off URS, donator only tools, or hell, even just tool logging. *What's worse* is that it's not even *consistent*. Hooks are first-come, first-serve on a good day, but when you start removing them, it becomes apparent that **hooks are unordered**. By adding this layer of unpredictability, you only exacerbate the problem of "Mostly you cannot exactly say, which addon produces the error."

**Comment by Domii894** [comment]
https://github.com/Patcher56/PatchProtect/commit/edb427335a48dadfd6e410f37944992b04c6fa2b
I hope you are fine with it.

**Comment by SpencerSharkey** [comment]
Why didn't you just merge & :ship: these commits.
:100:

**Comment by Domii894** [comment]
Because he didn't change all lines, where it comes to that situation. (He just did it for "tool". Not for "use", "property", ...).
Also there could be a better name for that change, right?

**Pull request closed without merging**
