### PR TITLE
Add default blocked props list

### PR DESCRIPTION
**Pull request by zaknes**
I was looking for a default list of props that I could import but I could not find one.

I spent a little while adding all of these props to the `blocked props` list on my server. After some tricky SQLite management, I was able to compile a list of blocked models.

I also updated the documentation to point this out.

### CODE REVIEW

**Comment by Domii894** [comment]
Nice job :)

thanks for that

**Comment by zaknes** [comment]
No problem!

I will mount TF2 to my server so I can block props from there, too. I remember TF2 having some unusually large props.

**Comment by Domii894** [comment]
ok.

Just make a new pull request please and i'll merge it then

**Comment by zaknes** [comment]
@Domii894 Yup!

**Pull request merged**
